export default image = {
   "abbott s babbler":require('../Abbottsbabbler.jpeg'),
   "aberrant bush warbler":require('../AberrantBushWarbler.jpeg'),
   "african comb duck":require('../AfricanCombDuck.jpeg'),
   "alexandrine parakeet":require('../AlexandrineParakeet.jpeg'),
   "alpine acentor":require('../AlpineAccentor.jpeg'),
   "alpine swift":require('../AlpineSwift.jpeg'),
   "alpine thrush":require('../AlpineThrush.jpeg'),
   "altai acentor":require('../AltaiAccentor.jpeg'),
   "amur falcon":require('../AmurFalcon.jpeg'),
   "ashy bulbul":require('../AshyBulbul.jpeg'),
   "ashy drongo":require('../AshyDrongo.jpeg'),
   "ashy minivet":require('../AshyMinivet.jpeg'),
   "ashy prinia":require('../AshyPrinia.jpeg'),
   "ashy wood pigeon":require('../AshyWoodPigeon.jpeg'),
   "ashy woodswallow":require('../AshyWoodswallow.jpeg'),
   "ashy headed green pigeon":require('../AshyHeadedGreenPigeon.jpeg'),
   "ashy crowned sparrow lark":require('../AshyCrownedSparrowLark.jpeg'),
   "ashy throated warbler":require('../AshyThroatedwarbler.jpeg'),
   "asian barred owlet":require('../AsianBarredOwlet.jpeg'),
   "asian blue quail":require('../AsianBlueQuail.jpeg'),
   "asian brown flycatcher":require('../AsianBrownFlycatcher.jpeg'),
   "asian emerald cuckoo":require('../AsianEmeraldCuckoo.jpeg'),
   "asian fairy bluebird":require('../AsianFairyBluebird.jpeg'),
   "asian glossy starling":require('../AsianGlossyStarling.jpeg'),
   "asian green bee eater":require('../AsianGreenBeeEater.jpeg'),
   "asian house martin":require('../AsianHouseMartin.jpeg'),
   "asian openbill":require('../AsianOpenbill.jpeg'),
   "asian palm swift":require('../AsianPalmSwift.jpeg'),
   "asian pied starling":require('../asianPiedStarling.jpeg'),
   "asian plain martin":require('../AsianPlainMartin.jpeg'),
   "asian stubtail":require('../AsianStubtail.jpeg'),
   "asian woollyneck":require('../asianWoollyneck.jpeg'),
   "baer s pochard":require('../BaersPochard.jpeg'),
   "baikal grasshopper warbler":require('../BaikalGrasshopperWarbler.jpeg'),
   "baikal teal":require('../BaikalTeal.jpeg'),
   "baillon s crake":require('../BaillonsCrake.jpeg'),
   "banded bay cuckoo":require('../BandedBayCuckoo.jpeg'),
   "bank myna":require('../BankMyna.jpeg'),
   "bar headed goose":require('../BarHeadedGoose.jpeg'),
   "bar tailed treecreper":require('../BartailedTreecreeper.jpeg'),
   "bar throated minla":require('../BarThroatedMinla.jpeg'),
   "bar winged flycatcher shrike":require('../BarwingedFlycatcherShrike.jpeg'),
   "barn swallow":require('../BarnSwallow.jpeg'),
   "barred buttonquail":require('../BarredButtonquail.jpeg'),
   "barred cuckoo dove":require('../BarredCuckooDove.jpeg'),
   "bay woodpecker":require('../BayWoodpecker.jpeg'),
   "bay backed shrike":require('../BayBackedShrike.jpeg'),
   "baya weaver":require('../BayaWeaver.jpeg'),
   "bean goose":require('../BeanGoose.jpeg'),
   "bearded vulture":require('../BeardedVulture.jpeg'),
   "beautiful rosefinch":require('../BeautifulRosefinch.jpeg'),
   "bengal bushlark":require('../BengalBushlark.jpeg'),
   "bengal florican":require('../BengalFlorican.jpeg'),
   "besra":require('../Besra.jpeg'),
   "black baza":require('../BlackBaza.jpeg'),
   "black bittern":require('../BlackBittern.jpeg'),
   "black bulbul":require('../BlackBulbul.jpeg'),
   "black drongo":require('../BlackDrongo.jpeg'),
   "black eagle":require('../BlackEagle.jpeg'),
   "black francolin":require('../BlackFrancolin.jpeg'),
   "black kite":require('../BlackKite.jpeg'),
   "black redstart":require('../BlackRedstart.jpeg'),
   "black strok":require('../BlackStrok.jpeg'),
   "black and yellow grosbeak":require('../BlackandYellowGrosbeak.jpeg'),
   "black backed forktail":require('../BlackbackedForktail.jpeg'),
   "black bellied tern":require('../BlackBelliedTern.jpeg'),
   "black breasted parrotbill":require('../BlackbreastedParrotbill.jpeg'),
   "black breasted weaver":require('../BlackbreastedWeaver.jpeg'),
   "black browed reed warbler":require('../BlackbrowedReedWarbler.jpeg'),
   "black capped kingfisher":require('../BlackcappedKingfisher.jpeg'),
   "black chinned babbler":require('../BlackChinnedBabbler.jpeg'),
   "black chinned yuhina":require('../BlackChinnedYuhina.jpeg'),
   "black crested bulbul":require('../BlackCrestedBulbul.jpeg'),
   "black crowned night heron":require('../BlackCrownedNightHeron.jpeg'),
   "black eared shrike babbler":require('../BlackearedShrikeBabbler.jpeg'),
   "black faced bunting":require('../BlackFacedBunting.jpeg'),
   "black faced laughingthrush":require('../BlackFacedLaughingThrush.jpeg'),
   "black faced warbler":require('../BlackFacedWarbler.jpeg'),
   "black headed bunting":require('../BlackheadedBunting.jpeg'),
   "black headed cuckooshrike":require('../BlackheadedCuckooshrike.jpeg'),
   "black headed gull":require('../blackHeadedGull.jpeg'),
   "black headed ibis":require('../BlackHeadedIbis.jpeg'),
   "black headed jay":require('../BlackHeadedJay.jpeg'),
   "black headed shrike babbler":require('../BlackheadedShrikebabbler.jpeg'),
   "black hooded oriole":require('../BlackHoodedOriole.jpeg'),
   "black lored tit":require('../BlackLoredTit.jpeg'),
   "black naped monarch":require('../BlacknapedMonarch.jpeg'),
   "black naped oriole":require('../BlackNapedOriole.jpeg'),
   "black naped woodpecker":require('../BlackNapedWoodpecker.jpeg'),
   "black necked crane":require('../BlackNeckedCrane.jpeg'),
   "black necked grebe":require('../BlackNeckedGrebe.jpeg'),
   "black necked stork":require('../BlackNeckedStrok.jpeg'),
   "black rumped flameback":require('../BlackRumpedFlameback.jpeg'),
   "black tailed godwit":require('../BlackTailedGodwit.jpeg'),
   "black throated accentor":require('../BlackThroatedAccentor.jpeg'),
   "black throated parrotbill":require('../BlackthroatedParrotbill.jpeg'),
   "black throated prinia":require('../BlackThroatedPrinia.jpeg'),
   "black throated sunbird":require('../BlackThroatedSunbird.jpeg'),
   "black throated thrush":require('../BlackThroatedThrush.jpeg'),
   "black trailed crake":require('../BlackTrailedCrake.jpeg'),
   "black winged cuckooshrike":require('../BlackWingedCuckooshrike.jpeg'),
   "black winged kite":require('../BlackwingedKite.jpeg'),
   "black winged snowfinch":require('../BlackWingedSnowfinch.jpeg'),
   "black winged stilt":require('../BlackWingedStilt.jpeg'),
   "blackish breasted babbler":require('../BlackishBreastedBabbler.jpeg'),
   "blanford s rosefinch":require('../BlanfordsRosefinch.jpeg'),
   "blood phesant":require('../BloodPheasant.jpeg'),
   "blosson headed parakeet":require('../BlossomHeadedParakeet.jpeg'),
   "blue bearded bee eater":require('../BluebeardedBeeEater.jpeg'),
   "blue capped redstart":require('../BluecappedRedstart.jpeg'),
   "blue capped rock thrush":require('../BlueCappedRockThrush.jpeg'),
   "blue eared barbet":require('../BlueEaredBarbet.jpeg'),
   "blue eared kingfisher":require('../BlueEaredKingfisher.jpeg'),
   "blue fronted redstart":require('../BlueFrontedRedstart.jpeg'),
   "blue naped pitta":require('../BlueNapedPitta.jpeg'),
   "blue rock thrush":require('../BlueRockThrush.jpeg'),
   "blue tailed bee eater":require('../BlueTailedBeeEater.jpeg'),
   "blue throated barbet":require('../BlueThroatedBarbet.jpeg'),
   "blue throated blue flycatcher":require('../BlueThroatedBlueFlycatcher.jpeg'),
   "blue whistling thrush":require('../BlueWhistlingThrush.jpeg'),
   "blue winged laughingthrush":require('../BlueWingedLaughingthrush.jpeg'),
   "blue winged minla":require('../BlueWingedMinla.jpeg'),
   "bluethroat":require('../Bluethroat.jpeg'),
   "blunt winged warbler":require('../BluntwingedWarbler.jpeg'),
   "blyth s kingfisher":require('../BlythsLeafWarbler.jpeg'),
   "blyth s leaf warbler":require('../BlythsLeafWarbler.jpeg'),
   "blyth s pipit":require('../BlythsPipit.jpeg'),
   "blyth s reed warbler":require('../BlythsReedWarbler.jpeg'),
   "bohemian waxwing":require('../BohemianWaxwing.jpeg'),
   "bonelli s eagle":require('../BonelliEagle.jpeg'),
   "booted eagle":require('../BootedEagle.jpeg'),
   "booted warbler":require('../BootedWarbler.jpeg'),
   "brahminy kite":require('../BrahminyKite.jpeg'),
   "brahminy starling":require('../BrahminyStarling.jpeg'),
   "brambling":require('../Brambling.jpeg'),
   "brandt s mountain finch":require('../BrandtsMountainFinch.jpeg'),
   "bristled grassbird":require('../BristledGrassbird.jpeg'),
   "broad billed warbler":require('../BroadBilledWarbler.jpeg'),
   "broen headed gull":require('../BrownheadedGull.jpeg'),
   "bronze drongo":require('../BronzedDrongo.jpeg'),
   "bronze winged jacana":require('../BronzeWingedJacana.jpeg'),
   "brown accentor":require('../BrownAccentor.jpeg'),
   "brown boobook":require('../BrownBoobook.jpeg'),
   "brown breasted flycatcher":require('../BrownbreastedFlycatcher.jpeg'),
   "brown bullfinch":require('../BrownBullfinch.jpeg'),
   "brown crake":require('../BrownCrake.jpeg'),
   "brown dipper":require('../BrownDipper.jpeg'),
   "brown fish owl":require('../BrownFishOwl.jpeg'),
   "brown fronted woodpecker":require('../BrownFrontedWoodpecker.jpeg'),
   "brown grasshopper warbler":require('../BrownGrasshopperWarbler.jpeg'),
   "brown headed barbet":require('../BrownHeadedBarbet.jpeg'),
   "brown parrotbill":require('../BrownParrotbill.jpeg'),
   "brown rockchat":require('../BrownRockChat.jpeg'),
   "brown shrike":require('../BrownShrike.jpeg'),
   "brown wood owl":require('../BrownWoolOwl.jpeg'),
   "brownish flanked bush warbler":require('../BrownishFlankedBushWarbler.jpeg'),
   "buff barred warbler":require('../BuffbarredWarbler.jpeg'),
   "buff bellied pipit":require('../BuffBelliedPipit.jpeg'),
   "caspian tern":require('../CaspianTern.jpeg'),
   "cattle egret":require('../CattleEgret.jpeg'),
   "changeable hawk eagle":require('../ChangeableHAwkEagle.jpeg'),
   "cheer plesant":require('../CheekPheasant.jpeg'),
   "chestnu bellied rock thrush":require('../ChestnutBelliedRockThrush.jpeg'),
   "chestnut bellied nuthatch":require('../ChestnutBelliedNuthatch.jpeg'),
   "chestnut bunting":require('../ChestnutBunting.jpeg'),
   "chestnut capped babbler":require('../ChestnutCappedBabbler.jpeg'),
   "chestnut crowned bush warbler":require('../ChestnutCrownedBushWarbler.jpeg'),
   "chestnut crowned laughingthrush":require('../ChestnutCrownedLaughingthrush.jpeg'),
   "chestnut crowned warbler":require('../ChestnutCrownedWarbler.jpeg'),
   "chestnut eared bunting":require('../ChestnutearedBunting.jpeg'),
   "chestnut headed bee eater":require('../ChestnutHeadedBeeEater.jpeg'),
   "chestnut headed tesia":require('../ChestnutHeadedTesia.jpeg'),
   "chestnut munia":require('../ChestnutMunia.jpeg'),
   "chestnut shouldered bush sparrow":require('../ChestnutShoulderedBushSparrow.jpeg'),
   "chestnut tailed starling":require('../ChestnutTailedStarling.jpeg'),
   "chestnut thrush":require('../ChestnutThrush.jpeg'),
   "chestnut winged cuckoo":require('../ChestnutWingedCuckoo.jpeg'),
   "chinese grasshopper warbler":require('../ChineseGrasshopperWarbler.jpeg'),
   "chinese rubythroat":require('../ChineseRubythroat.jpeg'),
   "chinese spot billed duck":require('../ChineseSpotBilledDuck.jpeg'),
   "chukar":require('../Chukar.jpeg'),
   "cinereous vulture":require('../CinereousVulture.jpeg'),
   "cinnamon bittern":require('../CinnamonBittern.jpeg'),
   "citrine wagtail":require('../CitrineWagtail.jpeg'),
   "clamorous reed warbler":require('../ClamorousReedWarbler.jpeg'),
   "cmmon coot":require('../CommonCoot.jpeg'),
   "coal tit":require('../CoalTit.jpeg'),
   "collard scops owl":require('../CollaredScopsOwl.jpeg'),
   "collared falconet":require('../CollaredFalconet.jpeg'),
   "collared groasbeak":require('../CollaredGroabeak.jpeg'),
   "collared owlet":require('../CollaredOwlet.jpeg'),
   "collared sand martin":require('../CollaredSandMartin.jpeg'),
   "common babbler":require('../CommonBabbler.jpeg'),
   "common barn owl":require('../CommonBarnOwl.jpeg'),
   "common buttonquail":require('../CommonButtonquail.jpeg'),
   "common chaffinch":require('../CommonChaffinch.jpeg'),
   "common crane":require('../CommonCrane.jpeg'),
   "common cuckoo":require('../CommonCuckoo.jpeg'),
   "common goldeneye":require('../CommonGoldeneye.jpeg'),
   "common grasshopper warbler":require('../CommonGrasshopperWarbler.jpeg'),
   "common green magpie":require('../CommonGreenMagpie.jpeg'),
   "common greenshank":require('../CommonGreenshank.jpeg'),
   "common hawk cuckoo":require('../CommonHawkCuckoo.jpeg'),
   "common hill myna":require('../CommonHillMyna.jpeg'),
   "common hoopoe":require('../CommonHoopoe.jpeg'),
   "common iora":require('../CommonIora.jpeg'),
   "common kestrel":require('../CommonKestrel.jpeg'),
   "common kingfisher":require('../CommonKingfisher.jpeg'),
   "common linnet":require('../CommonLinnet.jpeg'),
   "common moorhen":require('../CommonMoorhen.jpeg'),
   "common myna":require('../CommonMyna.jpeg'),
   "common pochard":require('../CommonPochard.jpeg'),
   "common quail":require('../CommonQuail.jpeg'),
   "common raven":require('../CommonRaven.jpeg'),
   "common redshank":require('../CommonRedshank.jpeg'),
   "common rosefinch":require('../CommonRosefinch.jpeg'),
   "common sandpiper":require('../CommonSandpiper.jpeg'),
   "common shelduck":require('../CommonShelduck.jpeg'),
   "common snipe":require('../CommonSnipe.jpeg'),
   "common starling":require('../CommonStarling.jpeg'),
   "common stonechat":require('../CommonStoneChat.jpeg'),
   "common swift":require('../CommonSwift.jpeg'),
   "common tailorbird":require('../CommonTailorbird.jpeg'),
   "common teal":require('../CommonTeal.jpeg'),
   "common tern":require('../CommonTern.jpeg'),
   "common woodpigeon":require('../CommonWoodpigeon.jpeg'),
   "common woodshrike":require('../CommonWoodshrike.jpeg'),
   "coppersmith barbet":require('../CoppersmithBarbet.jpeg'),
   "coral billed scimitar babbler":require('../CoralBilledScimitarBabbler.jpeg'),
   "cotton pygmy goose":require('../CottonPygmygoose.jpeg'),
   "creasted serpent eagle":require('../CrestedSerpentEagle.jpeg'),
   "crested bunting":require('../CrestedBunting.jpeg'),
   "crested goshawk":require('../CrestedBunting.jpeg'),
   "crested kingfisher":require('../CrestedKingfisher.jpeg'),
   "crested lark":require('../CrestedLArk.jpeg'),
   "crested treeswift":require('../CrestedTreeswift.jpeg'),
   "crimson browed finch":require('../CrimsonBrowedFinch.jpeg'),
   "crimson sunbird":require('../CrimsonSunbird.jpeg'),
   "crow billied drongo":require('../CrowBilledDrongo.jpeg'),
   "curlew sandpiper":require('../CurlewSandpiper.jpeg'),
   "darjeeling woodpecker":require('../DarjeelingWoodpecker.jpeg'),
   "dark breasted rosefinch":require('../DarkbreastedRosefinch.jpeg'),
   "dark rumped rosefinch":require('../DarkRumpedRosefinch.jpeg'),
   "dark sided flycatcher":require('../DarkSidedFlycatcher.jpeg'),
   "dark sided thrush":require('../DarkSidedThrush.jpeg'),
   "daurian redstart":require('../DaurianRedstart.jpeg'),
   "demoiselle crane":require('../DemoiselleCrane.jpeg'),
   "desert wheatear":require('../DesertWheatear.jpeg'),
   "dunlin":require('../Dunlin.jpeg'),
   "dusky thrush":require('../DuskyThrush.jpeg'),
   "dusky warbler":require('../DuskyWarbler.jpeg'),
   "dusty eagle owl":require('../DuskyEagleOwl.jpeg'),
   "easter marsh harrier":require('../EasternMarshHarrier.jpeg'),
   "eastern goldfinch":require('../EasternGoldfinch.jpeg'),
   "eastern grass owl":require('../EasternGrassOwl.jpeg'),
   "eastern imperial eagle":require('../EasternImperialEagle.jpeg'),
   "eastern orphean warbler":require('../EasternOrpheanWarbler.jpeg'),
   "egyptian vulture":require('../EgyptianVulture.jpeg'),
   "estern water rail":require('../EasternWaterRail.jpeg'),
   "eurasian bittern":require('../EurasianBittern.jpeg'),
   "eurasian collared dove":require('../EurasianCollaredDove.jpeg'),
   "eurasian crag martin":require('../EurasianCragMartin.jpeg'),
   "eurasian curlew":require('../EurasianCurlew.jpeg'),
   "eurasian eagle owl":require('../EurasianEagleOwl.jpeg'),
   "eurasian hobby":require('../EurasianHobby.jpeg'),
   "eurasian oystercatcher":require('../EurasianOystercatcher.jpeg'),
   "eurasian siskin":require('../EurasianSiskin.jpeg'),
   "eurasian skylark":require('../EurasianSkylark.jpeg'),
   "eurasian sparrowhawk":require('../EurasianSparrowhawk.jpeg'),
   "eurasian spoonbill":require('../EurasianSponbill.jpeg'),
   "eurasian tree sparrow":require('../EurasianTreeSparrow.jpeg'),
   "eurasian wigeon":require('../EurasianWigeon.jpeg'),
   "eurasian wookcock":require('../EurasianWoodcock.jpeg'),
   "eurasian wryneck":require('../EurasianWryneck.jpeg'),
   "eversmann s redstart":require('../EversmannsRedstart.jpeg'),
   "eyebrowed thrush":require('../EyebrowedThruch.jpeg'),
   "falcated duck":require('../FalcatedDuck.jpeg'),
   "ferruginous duck":require('../FerruginousDuck.jpeg'),
   "ferruginous flycatcher":require('../FerruginousFlycatcher.jpeg'),
   "finn s weaver":require('../FinnsWeaver.jpeg'),
   "fire breasted flowerpecker":require('../FireBreastedFlowerpecker.jpeg'),
   "fire capped tit":require('../FireCappedTit.jpeg'),
   "fire tailed myzornis":require('../FireTailedMyzonnis.jpeg'),
   "fire tailed sunbird":require('../FireTailedSunbird.jpeg'),
   "forest wagtail":require('../ForestWagtail.jpeg'),
   "fork tailed drongo cuckoo":require('../ForkTailedDrongoCuckoo.jpeg'),
   "fulvous breasted woodpecker":require('../FluvousBrestedWoodpecker.jpeg'),
   "fulvous parrotbill":require('../FulvousParrotbill.jpeg'),
   "fulvous whistling duck":require('../FluvousWhistlingDuck.jpeg'),
   "gadwall":require('../Gadwall.jpeg'),
   "garganey":require('../Garganey.jpeg'),
   "glossy ibis":require('../GlossyIbis.jpeg'),
   "gold naped finch":require('../GoldenNapedFinch.jpeg'),
   "golden babbler":require('../GoldenBabbler.jpeg'),
   "golden breasted fulvetta":require('../GoldenBreastedFulvetta.jpeg'),
   "golden bush robin":require('../Goldenbushrobin.jpeg'),
   "golden eagle":require('../GoldenEagle.jpeg'),
   "golden fronted leafbird":require('../GoldenFrontedLeafbird.jpeg'),
   "golden headed cisticola":require('../GoldenHeadedCisticola.jpeg'),
   "golden throated barbet":require('../GoldenThroatedBarbet.jpeg'),
   "goldrest":require('../Goldcrest.jpeg'),
   "goosander":require('../Goosander.jpeg'),
   "gould s shortwing":require('../GouldsShortwing.jpeg'),
   "gould s sunbird":require('../GouldsSunbird.jpeg'),
   "graceful prinia":require('../GracefulPrinia.jpeg'),
   "grandala":require('../Grandala.jpeg'),
   "great barbet":require('../GreatBarbet.jpeg'),
   "great cormorant":require('../GreatCormorant.jpeg'),
   "great created grebe":require('../GreatCrestedGrebe.jpeg'),
   "great grey shrike":require('../GreatGreyShrike.jpeg'),
   "great hornbill":require('../GreatHornbill.jpeg'),
   "great myna":require('../GreatMyna.jpeg'),
   "great parrotbill":require('../GreatParrotbill.jpeg'),
   "great rosefinch":require('../GreatRosefinch.jpeg'),
   "great staty woodpecker":require('../GreatSlatyWoodpecker.jpeg'),
   "great thick knee":require('../GreatThickKnee.jpeg'),
   "great tit":require('../GreatTit.jpeg'),
   "great white egret":require('../GreatwhiteEgret.jpeg'),
   "great white pelican":require('../GreatWhitePelican.jpeg'),
   "greater adjutant":require('../GreaterAdjutant.jpeg'),
   "greater coucal":require('../GreaterCoucal.jpeg'),
   "greater flameback":require('../GreaterFlameback.jpeg'),
   "greater flamingo":require('../GreaterFlamingo.jpeg'),
   "greater necklaced laughingthrush":require('../GreaterNecklacedLaughingthrush.jpeg'),
   "greater painted snipe":require('../GreaterPaintedSnipe.jpeg'),
   "greater racquet tailed drongo":require('../GreaterRacquetTailedDrongo.jpeg'),
   "greater sandplover":require('../GreaterSandplover.jpeg'),
   "greater scaup":require('../GreaterScaup.jpeg'),
   "greater short toed lark":require('../GreaterShortToedLark.jpeg'),
   "greater spotted eagle":require('../GreaterSpottedEagle.jpeg'),
   "greater white fronted goose":require('../GreaterWhiteFrontedGoose.jpeg'),
   "greater yellownape":require('../GreaterYellownape.jpeg'),
   "green backed herono":require('../GreenBackedHeron.jpeg'),
   "green backed tit":require('../GreenBackedTit.jpeg'),
   "green billed malkoha":require('../GreenBilledMalkoha.jpeg'),
   "green cochoa":require('../GreenCohoa.jpeg'),
   "green crowned warbler":require('../GreenCrownedWarbler.jpeg'),
   "green sandpiper":require('../GreenSandpiper.jpeg'),
   "green shrike babbler":require('../GreenShrikeBabbler.jpeg'),
   "green tailed sunbird":require('../GreenTailedSunbird.jpeg'),
   "green warbler":require('../GreenWarbler.jpeg'),
   "greenish warbler":require('../GreenishWarbler.jpeg'),
   "grey backed shrike":require('../GreyBackedShrike.jpeg'),
   "grey bellied cuckoo":require('../GreyBelliedCuckoo.jpeg'),
   "grey bellied tesia":require('../GreyBelliedTesia.jpeg'),
   "grey breasted prinia":require('../GreyBreastedPrinia.jpeg'),
   "grey browed broadbill":require('../GreybrowedBroadbill.jpeg'),
   "grey bushchat":require('../Greybushchat.jpeg'),
   "grey capped emerald dove":require('../GreyCappedEmeraldDove.jpeg'),
   "grey cheeked warbler":require('../GreycheekedWarbler.jpeg'),
   "grey chinned minivet":require('../GreyChinnedMinivet.jpeg'),
   "grey cpped woodpecker":require('../GreyCappedWoodpecker.jpeg'),
   "grey crested tit":require('../GreycrestedTit.jpeg'),
   "grey crowned prinia":require('../GreyCrownedPrinia.jpeg'),
   "grey francolin":require('../GreyFrancolin.jpeg'),
   "grey headed bullfinch":require('../GreyheadedBullfinch.jpeg'),
   "grey headed canary flycatcher":require('../GreyHeadedCanaryFlycatcher.jpeg'),
   "grey headed fish eagle":require('../GreyheadedFishEagle.jpeg'),
   "grey headed lapwing":require('../GreyHeadedLapwing.jpeg'),
   "grey heron":require('../GreyHeron.jpeg'),
   "grey hooded warbler":require('../GreyHoodedWarbler.jpeg'),
   "grey necked bunting":require('../GreynackedBunting.jpeg'),
   "grey nightjar":require('../GreyNightjar.jpeg'),
   "grey plover":require('../GreyPlover.jpeg'),
   "grey sided bush warbler":require('../GreySidedBushWarbler.jpeg'),
   "grey sided laughingthrush":require('../GreysidedLaughingThrush.jpeg'),
   "grey sided thrush":require('../GreysidedThrush.jpeg'),
   "grey throated babbler":require('../GreyThroatedBabbler.jpeg'),
   "grey treepie":require('../GreyTreepie.jpeg'),
   "grey wagtail":require('../GreyWagtail.jpeg'),
   "grey winged blackbird":require('../GreyWingedBlackbird.jpeg'),
   "greylag goose":require('../GreylagGoose.jpeg'),
   "griffon vulture":require('../GriffonVulture.jpeg'),
   "ground tit":require('../GroundTit.jpeg'),
   "gul billed tern":require('../GullbelliedTern.jpeg'),
   "hair crested drongo":require('../HairCrestedDrongo.jpeg'),
   "hen harrier":require('../HenHarrier.jpeg'),
   "hil partridge":require('../HillPartridge.jpeg'),
   "hill pigeon":require('../HillPigeon.jpeg'),
   "himalayan bulbul":require('../HimalayanBulbul.jpeg'),
   "himalayan bush robin":require('../HimalayanBushRobin.jpeg'),
   "himalayan buzzard":require('../HimalayanBuzzard.jpeg'),
   "himalayan cutia":require('../HimalayanCutia.jpeg'),
   "himalayan flameback":require('../HimalayanFlameback.jpeg'),
   "himalayan grasshopper warbler":require('../HimalayanGrasshopperWarbler.jpeg'),
   "himalayan griffon":require('../HimalayanGriffon.jpeg'),
   "himalayan monal":require('../HimalayanMonal.jpeg'),
   "himalayan owl":require('../HimalayanOwl.jpeg'),
   "himalayan rubythroat":require('../HimalayanRubythroat.jpeg'),
   "himalayan shortwing":require('../HimalayanShortwing.jpeg'),
   "himalayan snowcock":require('../HimalayanSnowcock.jpeg'),
   "himalayan swiftlet":require('../HimlayanSwiftlet.jpeg'),
   "himalayan white browed rosefinch":require('../HimalayanWhiteBrowedRosefinch.jpeg'),
   "himalayan woodpecker":require('../HimalayanWoodpecker.jpeg'),
   "hoary throated barwing":require('../HoaryThroatedBArwing.jpeg'),
   "hodgso s treecreeper":require('../HodgsonsTreecreeper.jpeg'),
   "hodgson s redstart":require('../HodgsonsRedstart.jpeg'),
   "horned lark":require('../HornedLArk.jpeg'),
   "horsfield s bushlark":require('../HorsfieldBushlark.jpeg'),
   "house crow":require('../HouseCrow.jpeg'),
   "house sparrow":require('../HouseSparrow.jpeg'),
   "house swift":require('../HouseSwift.jpeg'),
   "hume s bush warbler":require('../HumesBushWarbler.jpeg'),
   "hume s lark":require('../HumesLark.jpeg'),
   "hume s leaf warbler":require('../HumesLeafWarbler.jpeg'),
   "ibisbill":require('../Ibisbill.jpeg'),
   "immediate egret":require('../IntermediateEgret.jpeg'),
   "indian blue robin":require('../IndianBlueRobin.jpeg'),
   "indian cormorant":require('../IndianCormorant.jpeg'),
   "indian courser":require('../IndianCourser.jpeg'),
   "indian cuckoo":require('../IndianCuckoo.jpeg'),
   "indian cuckooshrike":require('../IndianCuckooshrike.jpeg'),
   "indian golden oriole":require('../IndianGoldenOriole.jpeg'),
   "indian grass bibbler":require('../IndianGrassbabbler.jpeg'),
   "indian grey hornbill":require('../IndianGreyHornbill.jpeg'),
   "indian nightjar":require('../IndianNightjar.jpeg'),
   "indian nuthatch":require('../IndianNuthatch.jpeg'),
   "indian paradise flycatcher":require('../IndianParadiseFlycatcher.jpeg'),
   "indian peafowl":require('../IndianPeafowl.jpeg'),
   "indian pitta":require('../IndianPitta.jpeg'),
   "indian pond heron":require('../IndianPondHeron.jpeg'),
   "indian pygmy woodpecker":require('../IndianPygmyWoodpecker.jpeg'),
   "indian robin":require('../IndianRobin.jpeg'),
   "indian roller":require('../IndianRoller.jpeg'),
   "indian scops owl":require('../IndianScopsOwl.jpeg'),
   "indian silverbill":require('../IndianSilverbill.jpeg'),
   "indian skimmer":require('../IndianSkimmer.jpeg'),
   "indian spot billed duck":require('../IndianSpotBilledDuck.jpeg'),
   "indian spotted eagle":require('../IndianSpottedEagle.jpeg'),
   "indian thick knee":require('../IndianThickKnee.jpeg'),
   "indian vulture":require('../IndianVulture.jpeg'),
   "indochinese roller":require('../IndochineseRoller.jpeg'),
   "isabelline shrike":require('../IsabelllineShrike.jpeg'),
   "isabelline wheatear":require('../IsabellinedWheatear.jpeg'),
   "jack snipe":require('../JackSnipe.jpeg'),
   "jacobin cuckoo":require('../JacobinCuckoo.jpeg'),
   "jerdon s babbler":require('../JerdonsBabbler.jpeg'),
   "jerdon s baza":require('../JerdonsBaza.jpeg'),
   "jerdon s bushchat":require('../JerdonsBushchat.jpeg'),
   "jungle babbler":require('../JungleBabbler.jpeg'),
   "jungle bush quail":require('../JunglebushQuail.jpeg'),
   "jungle myna":require('../JungleMyna.jpeg'),
   "jungle owlet":require('../JungleOwlet.jpeg'),
   "jungle prinia":require('../JunglePrinia.jpeg'),
   "kalij pleasant":require('../KalijPheasant.jpeg'),
   "kashmir flycatcher":require('../KashmirFlycatcher.jpeg'),
   "kashmir nuthatch":require('../KashmirNuthatch.jpeg'),
   "kentish plover":require('../KentishPlover.jpeg'),
   "koklass phesant":require('../KoklassPheasant.jpeg'),
   "lagger falcon":require('../LaggerFalcon.jpeg'),
   "lanceolated warbler":require('../LanceolatedWarbler.jpeg'),
   "large billed crow":require('../LargebilledCrow.jpeg'),
   "large billed leaf warbler":require('../LargebelliedLeafWarbler.jpeg'),
   "large grey babbler":require('../LargeGreyBabbler.jpeg'),
   "large hawk cuckoo":require('../LargeHawkCuckoo.jpeg'),
   "large niltava":require('../LargeNiltava.jpeg'),
   "large tailed nightjar":require('../LargeTailedNightjar.jpeg'),
   "large woodshrike":require('../LargeWoodshrike.jpeg'),
   "laughing dove":require('../LaughingDove.jpeg'),
   "lemon rumped leaf warbler":require('../LemonrumpedLeafWarbler.jpeg'),
   "lesser adjutant":require('../LesserAdjutant.jpeg'),
   "lesser black blacked gull":require('../LesserBackbackedGull.jpeg'),
   "lesser coucal":require('../LesserCoucal.jpeg'),
   "lesser cuckoo":require('../LesserCuckoo.jpeg'),
   "lesser fish eagle":require('../LesserFishEagle.jpeg'),
   "lesser florican":require('../LesserFlorican.jpeg'),
   "lesser kestrel":require('../LesserKestrel.jpeg'),
   "lesser necklaced laughingthrush":require('../LesserNecklacedLAughingthrush.jpeg'),
   "lesser racquet tailed drongo":require('../LesserRacquetTailedDrongo.jpeg'),
   "lesser sandplover":require('../LesserSandplover.jpeg'),
   "lesser shortwing":require('../LesserShortwing.jpeg'),
   "lesser whistling duck":require('../LesserWhistlingDuck.jpeg'),
   "lesser whitethroat":require('../LesserWhitethroat.jpeg'),
   "lesser yellownape":require('../LesserYellownape.jpeg'),
   "lineated barbet":require('../LineatedBarbet.jpeg'),
   "little bunting":require('../LittleBunting.jpeg'),
   "little cormorant":require('../LittleCormorant.jpeg'),
   "little egret":require('../LittleEgret.jpeg'),
   "little forktail":require('../LittleForktail.jpeg'),
   "little grebe":require('../LittleGrebe.jpeg'),
   "little owlet":require('../LittleOwl.jpeg'),
   "little pied flycatcher":require('../LittlePiedFlycatcher.jpeg'),
   "little pratincole":require('../LittlePraticole.jpeg'),
   "little ringed plover":require('../LittleRingedPlover.jpeg'),
   "little spiderhunter":require('../LittleSpiderhunter.jpeg'),
   "little stint":require('../LittleStint.jpeg'),
   "little tern":require('../LittleTern.jpeg'),
   "long billed pipit":require('../LongBelliedPipit.jpeg'),
   "long billed plover":require('../LongBilledPlover.jpeg'),
   "long billed thrush":require('../LongBilledThrush.jpeg'),
   "long billed wren babbler":require('../LongBilledWrenBabbler.jpeg'),
   "long legged buzzard":require('../LongLeggedBuzzard.jpeg'),
   "long tailed broadbill":require('../LongtailedBroadbill.jpeg'),
   "long tailed duck":require('../LongTailedDuck.jpeg'),
   "long tailed minivet":require('../LongTailedMinivet.jpeg'),
   "long tailed shrike":require('../LongTAiledShrike.jpeg'),
   "long tailed sibia":require('../LongTailedSibia.jpeg'),
   "long tailed thrush":require('../LongTailedThrush.jpeg'),
   "long toed stint":require('../LongToedStint.jpeg'),
   "malay night heron":require('../MalayaNightHeron.jpeg'),
   "mallard":require('../Mallard.jpeg'),
   "mandarin duck":require('../MandarianDuck.jpeg'),
   "maroon backed accentor":require('../MaroonBackedAccentor.jpeg'),
   "maroon oriole":require('../MaroonOriole.jpeg'),
   "marsh sandpiper":require('../MarshSandpiper.jpeg'),
   "merlin":require('../Merlin.jpeg'),
   "mew gull":require('../MewGull.jpeg'),
   "mistle thrush":require('../MistleThrush.jpeg'),
   "mongolian finch":require('../MongolianFinch.jpeg'),
   "montagu s harrier":require('../MontagusHarrier.jpeg'),
   "mottled wood owl":require('../MottledWoodOwl.jpeg'),
   "mountain bulbul":require('../MountainBulbul.jpeg'),
   "mountain imperial pigeon":require('../MountainImperialPigeon.jpeg'),
   "mountain scops owl":require('../MountainScopsOwl.jpeg'),
   "mountain tailorbird":require('../MountainTailorBird.jpeg'),
   "mountian hawk eagle":require('../MountainHawkEagle.jpeg'),
   "moustached warbler":require('../MoustachedWarbler.jpeg'),
   "nepal cupwing":require('../NepalCupwing.jpeg'),
   "nepal fulvetta":require('../NepalFulvetta.jpeg'),
   "nepal house martin":require('../NepalHouseMArtin.jpeg'),
   "noerthern shoveler":require('../NortherSholveler.jpeg'),
   "norther pintail":require('../NorthernPintail.jpeg'),
   "northern goshawk":require('../NorthernGoshawk.jpeg'),
   "northern house martin":require('../NorthernHouseMArtin.jpeg'),
   "northern lapwing":require('../NorthernLapwing.jpeg'),
   "northern long eared owl":require('../NorthernLongearedOwl.jpeg'),
   "northern wheatear":require('../NorthernWheatear.jpeg'),
   "northern wren":require('../NorthernWren.jpeg'),
   "olive backed pipit":require('../OlivebackedPipit.jpeg'),
   "orange bellied leafbird":require('../OrangebelliedLeafbird.jpeg'),
   "orange breasted green dove":require('../OrangeBreastedGreenPigeon.jpeg'),
   "orange headed thrush":require('../OrangeHeadedThrush.jpeg'),
   "oriental cuckoo":require('../OrientalCuckoo.jpeg'),
   "oriental darter":require('../OrientalDarter.jpeg'),
   "oriental dollarbird":require('../OrientalDollarbird.jpeg'),
   "oriental hobby":require('../OrientalHobby.jpeg'),
   "oriental honey buzzard":require('../OrientalHoneyBuzzard.jpeg'),
   "oriental magpie robin":require('../OrientalMagpieRoboin.jpeg'),
   "oriental pied hornbill":require('../OrientalPiedHornbill.jpeg'),
   "oriental reed warbler":require('../OrientalReedWarbler.jpeg'),
   "oriental scops owl":require('../OrientalScopsOwl.jpeg'),
   "oriental skylark":require('../OrientalSkylark.jpeg'),
   "oriental turtle dove":require('../OrientalTurtleDove.jpeg'),
   "oriental white eye":require('../OrientalWhiteeye.jpeg'),
   "orienteal pratincole":require('../OrientalPratincole.jpeg'),
   "osprey":require('../Osprey.jpeg'),
   "pacific golden plover":require('../PacificGoldenPlover.jpeg'),
   "pacific swift":require('../PacificSwift.jpeg'),
   "paddyfield pipit":require('../PaddyfieldPipit.jpeg'),
   "paddyfield warbler":require('../PaddyfieldWarbler.jpeg'),
   "painted stork":require('../PaintedStrok.jpeg'),
   "pale billed flowerpecker":require('../PaleBilledFlowerpecker.jpeg'),
   "pale blue flycatcher":require('../PaleBlueFlycatcher.jpeg'),
   "pale chinned flycatcher":require('../PaleChinnedFlycatcher.jpeg'),
   "pale footed bush warbler":require('../PalaFootedBushWArbler.jpeg'),
   "pale headed woodpecker":require('../PaleHeadedWoodpecker.jpeg'),
   "pale sand martin":require('../PaleSandMartin.jpeg'),
   "pallas s fish eagle":require('../PallasFishEagle.jpeg'),
   "pallas s grasshopper warbler":require('../PallassGrasshopperWarbler.jpeg'),
   "pallas s gull":require('../PallassGull.jpeg'),
   "pallid harrier":require('../PallidHarrier.jpeg'),
   "peregrine falcon":require('../PeregrineFalcon.jpeg'),
   "pheasant tailed jacana":require('../PheasantTailedJacana.jpeg'),
   "pied avocet":require('../PiedAvocet.jpeg'),
   "pied bushchat":require('../PiedBushChat.jpeg'),
   "pied harrier":require('../PiedHarrier.jpeg'),
   "pied kingfisher":require('../PiedKingfisher.jpeg'),
   "pied thrush":require('../PiedThrush.jpeg'),
   "pied wheatear":require('../PiedWheatear.jpeg'),
   "pin striped tit babbler":require('../PinStripedTitBabbler.jpeg'),
   "pin tailed green pigeon":require('../PintailedGreenPigeon.jpeg'),
   "pine bunting":require('../PineBunting.jpeg'),
   "pink browed rosefinch":require('../PinkBrowedRosefinch.jpeg'),
   "pink headed duck":require('../PinkheadedDuck.jpeg'),
   "pintail snipe":require('../PintailedSnipe.jpeg'),
   "plain backed snowfinch":require('../PlainBackedSnowfinch.jpeg'),
   "plain crowned jay":require('../PlainCrownedJay.jpeg'),
   "plain flowerpecker":require('../PlainFlowerpecker.jpeg'),
   "plain mountain finch":require('../PlainMountainFinch.jpeg'),
   "plain prinia":require('../PlainPrinia.jpeg'),
   "plaintive cuckoo":require('../PlaintiveCuckoo.jpeg'),
   "plum headed parakeet":require('../PlumHeadedParakeet.jpeg'),
   "plumbeous water redstart":require('../PlumbeousWaterRedstart.jpeg'),
   "puff throated babbler":require('../PuffThroatedBabbler.jpeg'),
   "purple backed starling":require('../PurpleBackedStarling.jpeg'),
   "purple cochoa":require('../PrupleCochoa.jpeg'),
   "purple heron":require('../PurpleHeron.jpeg'),
   "purple sunbird":require('../PurpleSunbird.jpeg'),
   "purple swamphen":require('../PurpleSwamphen.jpeg'),
   "pygmy blue flycatcher":require('../PygmyBlyeFlycatcher.jpeg'),
   "pygmy cupwing":require('../PygmyCupwing.jpeg'),
   "radde s warbler":require('../RaddesWarbler.jpeg'),
   "rain quail":require('../RainQuail.jpeg'),
   "red avadavat":require('../RedAvadat.jpeg'),
   "red billed blue magpie":require('../RedbilledBlueMagpie.jpeg'),
   "red billed chough":require('../RedbilledChough.jpeg'),
   "red billed leiothrix":require('../RedBilledLeiothrix.jpeg'),
   "red breasted flycatcher":require('../RedBreastedFlycatcher.jpeg'),
   "red breasted merganser":require('../RedBreastedMerganser.jpeg'),
   "red breated parakeet":require('../RedBreastedParakeet.jpeg'),
   "red creted pochard":require('../RedCrestedPochard.jpeg'),
   "red crossbill":require('../RedCrossbill.jpeg'),
   "red faced liocichla":require('../RedFacedLiocichla.jpeg'),
   "red fronted rosefinch":require('../RedfrontedRosefinch.jpeg'),
   "red fronted serin":require('../RedFrontedSerin.jpeg'),
   "red headed bullfinch":require('../RedheadedBullfinch.jpeg'),
   "red headed bunting":require('../RedheadedBunting.jpeg'),
   "red headed falcon":require('../RedHeadedFalcon.jpeg'),
   "red headed tit":require('../RedHeadedTit.jpeg'),
   "red headed trogon":require('../RedHeadedTrogon.jpeg'),
   "red headed vulture":require('../RedheadedVulture.jpeg'),
   "red junglefowl":require('../RedJungleFowl.jpeg'),
   "red knot":require('../RedKnot.jpeg'),
   "red naped ibis":require('../RedNapedIbis.jpeg'),
   "red necked phalarope":require('../redNeckedPhalarope.jpeg'),
   "red rumped swallow":require('../RedrumpedSwallow.jpeg'),
   "red tailed minla":require('../RedTailedMinla.jpeg'),
   "red tailed wheatear":require('../RedtailedWheatear.jpeg'),
   "red throated flycatcher":require('../RedThroatedFlycatcher.jpeg'),
   "red throated loon":require('../RedThroatedLoon.jpeg'),
   "red throated pipit":require('../RedThroatedPipit.jpeg'),
   "red turtle dove":require('../RedTurtleDove.jpeg'),
   "red vented bulbul":require('../RedVentedBulbul.jpeg'),
   "red wattled lapwing":require('../RedWattledLapwing.jpeg'),
   "red whiskered bulbul":require('../RedWhiskeredBulbul.jpeg'),
   "reed bunting":require('../ReedBunting.jpeg'),
   "richard s pipit":require('../RichardPipit.jpeg'),
   "river lapwing":require('../RiverLapwing.jpeg'),
   "river tern":require('../riverTern.jpeg'),
   "robin accentor":require('../RobinAccentor.jpeg'),
   "rock bunting":require('../RockBunting.jpeg'),
   "rock dove":require('../RockDove.jpeg'),
   "rock eagle owl":require('../RockEagleOwl.jpeg'),
   "rose ringed parakeet":require('../RoseRingedParakeet.jpeg'),
   "rosy minivet":require('../RosyMinivet.jpeg'),
   "rosy pipit":require('../RosyPipit.jpeg'),
   "rosy starling":require('../RosyStarling.jpeg'),
   "ruby cheeked sunbird":require('../RubyCheekedSunbird.jpeg'),
   "ruddy breasted crake":require('../RuddyBreastedCrake.jpeg'),
   "ruddy kingfisher":require('../RuddyKingfisher.jpeg'),
   "ruddy shelduck":require('../RuddyShelduck.jpeg'),
   "ruddy turnstone":require('../RuddyTurnstone.jpeg'),
   "ruff":require('../Ruff.jpeg'),
   "rufous backed sibia":require('../RufousBackedSibia.jpeg'),
   "rufous belied niltava":require('../RufousBelliedniltava.jpeg'),
   "rufous bellied eagle":require('../RufousBelliedEagle.jpeg'),
   "rufous bellied woodpecker":require('../RufousBelliedWoodpecker.jpeg'),
   "rufous breasted accentor":require('../RufousBreastedAccentor.jpeg'),
   "rufous breasted bush robin":require('../RufousbreastedBlueRobin.jpeg'),
   "rufous capped babbler":require('../RufousCappedBabbler.jpeg'),
   "rufous chinned laughingthrush":require('../RufousChinnedLaughingthrush.jpeg'),
   "rufous faced warbler":require('../RufousFacedWarbler.jpeg'),
   "rufous fronted tit":require('../RufousFrontedTit.jpeg'),
   "rufous gorgeted flycatcher":require('../RufousGorgetedFlycatcher.jpeg'),
   "rufous naped tit":require('../RufousNapedTit.jpeg'),
   "rufous necked hornbill":require('../RufousNeckedHornbill.jpeg'),
   "rufous necked laughingthrush":require('../RufousNeckedLaughingthrush.jpeg'),
   "rufous necked snowfinch":require('../RufousNeckedSnowfinch.jpeg'),
   "rufous sibia":require('../RufousSibia.jpeg'),
   "rufous tailed lark":require('../RufousTailedLark.jpeg'),
   "rufous tailed rock thrush":require('../RufousTailedRockThrush.jpeg'),
   "rufous throated partridge":require('../RufousThroatedPartridge.jpeg'),
   "rufous throated thrush":require('../RufousThroatedThrush.jpeg'),
   "rufous throated wren babbler":require('../RufousThroatedWrenBabbler.jpeg'),
   "rufous treepie":require('../RufousTreepie.jpeg'),
   "rufous vented tit":require('../RufousVentedTit.jpeg'),
   "rufous vented yuhina":require('../RufousVentedYuhina.jpeg'),
   "rufous winged fulvetta":require('../RufousWingedFulvetta.jpeg'),
   "rufous woodpecker":require('../RufousWoodpecker.jpeg'),
   "russet sparrow":require('../RussetSparrow.jpeg'),
   "rustic bunting":require('../RusticBunting.jpeg'),
   "rusty cheeked scimitar babbler":require('../RustyCheekedScimitarBabbler.jpeg'),
   "rusty flanked treecreeper":require('../RustyFlankedTreecreeper.jpeg'),
   "rusty fronted barwing":require('../RustyfrontedBarwing.jpeg'),
   "rusty tailed flycatcher":require('../RustyTailedFlycatcher.jpeg'),
   "saker falcon":require('../SakerFalcon.jpeg'),
   "sand lark":require('../SandLark.jpeg'),
   "sanderling":require('../Sanderling.jpeg'),
   "sapphire flycatcher":require('../SapphireFlycatcher.jpeg'),
   "sarus crane":require('../SarusCrane.jpeg'),
   "satyr tragopan":require('../SatyrTragopan.jpeg'),
   "savanna nightjar":require('../SavannaNightjar.jpeg'),
   "scaly bellied woodpecker":require('../ScalyBelliedWoodpecker.jpeg'),
   "scaly breasted cupwing":require('../ScalybreastedCupwing.jpeg'),
   "scaly breasted munia":require('../ScalyBreastedMunia.jpeg'),
   "scaly laughingthrush":require('../ScalyLaughingthrush.jpeg'),
   "scaly thrush":require('../ScalyThrush.jpeg'),
   "scarlet backed flowerpecker":require('../ScarletBackedFlowerpecker.jpeg'),
   "scarlet breasted woodpecker":require('../ScarletBreastedWoodpecker.jpeg'),
   "scarlet finch":require('../ScarletFinch.jpeg'),
   "scarlet minivet":require('../ScarletMinivet.jpeg'),
   "shikra":require('../Shikra.jpeg'),
   "short billed minivet":require('../ShortbilledMinivet.jpeg'),
   "short eared owl":require('../ShortEaredOWl.jpeg'),
   "short toed snake eagle":require('../ShortToedSnakeEagle.jpeg'),
   "siberian blue robin":require('../SiberianBlueRobin.jpeg'),
   "siberian chiffchaff":require('../SiberianChiffchaff.jpeg'),
   "siberian rubythroat":require('../SiberianRubythroat.jpeg'),
   "sikkim treecreeper":require('../SikkimTreecreeper.jpeg'),
   "silver backed needletail":require('../SilverBackedNeedletail.jpeg'),
   "silver eared mesia":require('../SilverEaredMesia.jpeg'),
   "sirkeer malkoha":require('../SirkeerMalkoha.jpeg'),
   "slatey legged crake":require('../SlatyLeggedCrake.jpeg'),
   "slaty backed flycatcher":require('../SlatybackedFlycatcher.jpeg'),
   "slaty backed forktail":require('../SlatyBackedForktail.jpeg'),
   "slaty bellied tesia":require('../SlatybelliedTesia.jpeg'),
   "slaty blue flycatcher":require('../SlatyBlueFlycatcher.jpeg'),
   "slaty breasted rail":require('../SlatyBreastedRail.jpeg'),
   "slaty headed parakeet":require('../SlatyHeadedParakeet.jpeg'),
   "slender billed babbler":require('../SlenderBilledBabbler.jpeg'),
   "slender billed gull":require('../SlenderbilledGull.jpeg'),
   "slender billed oriole":require('../SlenderBilledOriole.jpeg'),
   "slender billed scimitar babbler":require('../SlenderBilledScimitarBabbler.jpeg'),
   "slender billed vulture":require('../SlenderbilledVulture.jpeg'),
   "small minivet":require('../SmallMinivet.jpeg'),
   "small niltava":require('../SmallNiltava.jpeg'),
   "smew":require('../Smew.jpeg'),
   "smoky warbler":require('../SmokyWarbler.jpeg'),
   "snow partridge":require('../snowpartridge.jpeg'),
   "snow pigeon":require('../SnowPigeon.jpeg'),
   "snowy browed flycatcher":require('../SnowyBrowedFlycatcher.jpeg'),
   "solitary snipe":require('../SolitarySnipe.jpeg'),
   "sooty tern":require('../SootyTern.jpeg'),
   "southern nutcraker":require('../SouthernNutcraker.jpeg'),
   "spactacled finch":require('../Spectacledfinch.jpeg'),
   "spanish sparrow":require('../SpanishSparrow.jpeg'),
   "speckled piculet":require('../SpeckledPiculet.jpeg'),
   "speckled woodpigeon":require('../SpeckledWoodPigeon.jpeg'),
   "spiny babbler":require('../SpinyBabbler.jpeg'),
   "spot bellied eagle owl":require('../SpotbelliedEagleowl.jpeg'),
   "spot billed pelican":require('../SpotBilledPelican.jpeg'),
   "spot winged grosbeak":require('../SpotWingedGraobeak.jpeg'),
   "spot winged rosefinch":require('../SpotWingedRosefinch.jpeg'),
   "spot winged starling":require('../SpotWingedStarling.jpeg'),
   "spotted crake":require('../SpottedCrake.jpeg'),
   "spotted elachura":require('../SpottedElachura.jpeg'),
   "spotted forktail":require('../SpottedForktail.jpeg'),
   "spotted grasshopper warbler":require('../SpottedGrasshopperWarbler.jpeg'),
   "spotted laughingthrush":require('../SpottedLaughingthrush.jpeg'),
   "spotted owlet":require('../SpottedOwlet.jpeg'),
   "spotted redshank":require('../SpottedRedshank.jpeg'),
   "steppe eagle":require('../SteppeEagle.jpeg'),
   "stork billed kingfisher":require('../StorkBilledKingfisher.jpeg'),
   "streak breasted scimitar babbler":require('../StreakBreastedScimitarBabbler.jpeg'),
   "streak throated swallow":require('../StreakThroatedSwallow.jpeg'),
   "streak throated woodpecker":require('../StreakThroatedWoodpecker.jpeg'),
   "streaked laughingthrush":require('../StreakedLaughingthrush.jpeg'),
   "streaked rosefinch":require('../StreakedRosefinch.jpeg'),
   "streaked spiderhunter":require('../StreakedSpiderhunter.jpeg'),
   "streaked weaver":require('../StreakedWeaver.jpeg'),
   "striated babbler":require('../StriatedBabbler.jpeg'),
   "striated bulbul":require('../StriatedBulbul.jpeg'),
   "striated grassbird":require('../StriatedGrassbird.jpeg'),
   "striated laughingthrush":require('../StriatedLaughingthrush.jpeg'),
   "striated prinia":require('../StriatedPrinia.jpeg'),
   "stripe throated yuhina":require('../StripeThroatedYuhina.jpeg'),
   "sulphur bellied warbler":require('../SulphurBelliedWarbler.jpeg'),
   "sultan tit":require('../SultanTit.jpeg'),
   "swamp francolin":require('../SwampFrancolin.jpeg'),
   "swamp grass babbler":require('../SwampGrassBabbler.jpeg'),
   "swinhoe s minivet":require('../SwinhoesMinivet.jpeg'),
   "sykes s nightjar":require('../SykessNightjar.jpeg'),
   "tawny bellied babbler":require('../TawnyBelliedBabbler.jpeg'),
   "tawny eagle":require('../TawnyEagle.jpeg'),
   "tawny fish owl":require('../TawnyFishOwl.jpeg'),
   "tawny pipit":require('../TawnyPipit.jpeg'),
   "temminck s stint":require('../TemmincksStint.jpeg'),
   "terek sandpiper":require('../TerekSandpiper.jpeg'),
   "thick billed flowerpecker":require('../ThickBilledFlowerpecker.jpeg'),
   "thick billed green pigeon":require('../ThickBilledGreenPigeon.jpeg'),
   "thick billed warbler":require('../ThickbilledWarbler.jpeg'),
   "tibetan blackbird":require('../TibetanBlackbird.jpeg'),
   "tibetan lark":require('../TibetanLark.jpeg'),
   "tibetan partridge":require('../TibetanPartridge.jpeg'),
   "tibetan sandgrouse":require('../TibetanSandgrouse.jpeg'),
   "tibetan siskin":require('../TibetanSiskin.jpeg'),
   "tibetan snowcock":require('../TibetanSnowcock.jpeg'),
   "tickell s blue flycatcher":require('../TickellsBlueFlycatcher.jpeg'),
   "tickell s leaf warbler":require('../TickellsLeafWarbler.jpeg'),
   "tickell s thrush":require('../TickellsThrush.jpeg'),
   "tree pipit":require('../Treepipit.jpeg'),
   "tricolored munia":require('../Tricoloured.jpeg'),
   "tufted duck":require('../TuftedDuck.jpeg'),
   "tundra swan":require('../TundraSwan.jpeg'),
   "twite":require('../Twite.jpeg'),
   "tytler s leaf warbler":require('../TytlersLeafWarbler.jpeg'),
   "ultramarine flycatcher":require('../UltramarineFlycatcher.jpeg'),
}

const name = [
    // :require('../.jpeg')
    "upland buzzard",
    "upland pipit",
    "variable wheatear",
    "variegated laughingthrush",
    "velvet fronted nuthatch",
    "verditer flycatcher",
    "vernal hanging parrot",
    "vinaceous rosefinch",
    "wallcreeper",
    "water pipit",
    "watercock",
    "wedge tailed green pigeon",
    "western crowned leaf warbler",
    "western hooded pitta",
    "western koel",
    "western marsh harrier",
    "western spotted dove",
    "western water rail",
    "western yellow wagtail",
    "whimbrel",
    "whiskered tern",
    "whiskered yuhina",
    "whistler s warbler",
    "whistling hawk cuckoo",
    "white backed thrush",
    "white bellied drongo",
    "white bellied erponis",
    "white bellied heron",
    "white bellied redstart",
    "white breasted kingfisher",
    "white breasted waterhen",
    "white browed bush robin",
    "white browed fantail",
    "white browed fulvetta",
    "white browed scimitar babbler",
    "white browed shrike babbler",
    "white browed tit warbler",
    "white browed wagtail",
    "white browned piculet",
    "white capped bunting",
    "white capped water redstart",
    "white cheeked nuthatch",
    "white collared blackbird",
    "white crested laughingthrush",
    "white eyed buzzard",
    "white gorgeted flycatcher",
    "white hooded babbler",
    "white naped woodpecker",
    "white naped yuhina",
    "white rumped munia",
    "white rumped shama",
    "white rumped snowfinch",
    "white rumped spinetail",
    "white rumped vulture",
    "white shouldered starling",
    "white stork",
    "white tailed blue robin",
    "white tailed lapwing",
    "white tailed nuthatch",
    "white tailed sea eagle",
    "white tailed stonechat",
    "white throated bulbul",
    "white throated bushchat",
    "white throated dipper",
    "white throated fantail",
    "white throated laughingthrush",
    "white throated needletail",
    "white throated redstart",
    "white throated tit",
    "white wagtail",
    "white winged grosbeak",
    "white winged redstart",
    "white winged tern",
    "whooper swan",
    "wire tailed swallow",
    "wood sandpiper",
    "wood snipe",
    "yellow bellied fairy fantail",
    "yellow bellied flowerpecker",
    "yellow bellied prinia",
    "yellow bellied warbler",
    "yellow billed blue magpie",
    "yellow billed chough",
    "yellow bittern",
    "yellow breasted bunting",
    "yellow breasted greenfinch",
    "yellow browed tit",
    "yellow browed warbler",
    "yellow cheeked tit",
    "yellow crowned woodpecker",
    "yellow eyed babbler",
    "yellow footed green pigeon",
    "yellow legged buttonquail",
    "yellow rumped honeyguide",
    "yellow vented flowerpecker",
    "yellow vented warbler",
    "yellow wattled lapwing",
    "yellowhammer",
    "zitting cisticola"

]

    
