export default family={
    "Phasianidae":[
        "snow partridge",
        "hil partridge",
        "rufous throated partridge",
        "tibetan partridge",
        "common quail",
        "rain quail",
        "asian blue quail",
        "jungle bush quail",
        "himalayan snowcock",
        "tibetan snowcock",
        "chukar",
        "black francolin",
        "grey francolin",
        "swamp francolin",
        "indian peafowl",
        "red junglefowl",
        "himalayan monal",
        "satyr tragopan",
        "blood phesant",
        "koklass phesant",
        "cheer plesant",
        "kalij pleasant"
    ],
    "Anatidae":[
        "fulvous whistling duck",
        "lesser whistling duck",
        "whooper swan",
        "tundra swan",
        "bean goose",
        "greater white fronted goose",
        "greylag goose",
        "long tailed duck",
        "common goldeneye",
        "smew",
        "goosander",
        "red breasted merganser",
        "ruddy shelduck",
        "common shelduck",
        "african comb duck",
        "cotton pygmy goose",
        "red creted pochard",
        "common pochard",
        "baer s pochard",
        "ferruginous duck",
        "tufted duck",
        "greater scaup",
        "pink headed duck",
        "garganey",
        "noerthern shoveler",
        "bar headed goose",
        "falcated duck",
        "mandarin duck",
        "gadwall",
        "eurasian wigeon",
        "indian spot billed duck",
        "chinese spot billed duck",
        "mallard",
        "norther pintail",
        "common teal",
        "baikal teal"    
    ],
    "Podicipedidae":[
        "little grebe",
        "great created grebe",
        "black necked grebe"
    ],
    "Phoenicopteridae":[
        "greater flamingo"
    ],
    "Columbidae":[
        "rock dove",
        "hill pigeon",
        "snow pigeon",
        "common woodpigeon",
        "speckled woodpigeon",
        "ashy wood pigeon",
        "oriental turtle dove",
        "eurasian collared dove",
        "red turtle dove",
        "western spotted dove",
        "laughing dove",
        "barred cuckoo dove",
        "grey capped emerald dove",
        "orange breasted green dove",
        "ashy headed green pigeon",
        "thick billed green pigeon",
        "yellow footed green pigeon",
        "pin tailed green pigeon",
        "wedge tailed green pigeon",
        "mountain imperial pigeon"
    ],
    "Pteroclidae":[
        "tibetan sandgrouse"
    ],
    "Caprimulgidae":[
        "grey nightjar",
        "sykes s nightjar",
        "large tailed nightjar",
        "indian nightjar",
        "savanna nightjar"
    ],
    "Hemiprocnidae":[
        "crested treeswift"
    ],
    "Apodidae":[
        "white rumped spinetail",
        "white throated needletail",
        "silver backed needletail",
        "himalayan swiftlet",
        "asian palm swift",
        "alpine swift",
        "pacific swift",
        "house swift",
        "common swift"
    ],
    "Cuculidae":[
        "greater coucal",
        "lesser coucal",
        "sirkeer malkoha",
        "green billed malkoha",
        "jacobin cuckoo",
        "chestnut winged cuckoo",
        "western koel",
        "asian emerald cuckoo",
        "banded bay cuckoo",
        "grey bellied cuckoo",
        "fork tailed drongo cuckoo",
        "large hawk cuckoo",
        "common hawk cuckoo",
        "whistling hawk cuckoo",
        "indian cuckoo",
        "common cuckoo",
        "lesser cuckoo",
        "oriental cuckoo",
        "plaintive cuckoo"
    ],
    "Rallidae":[
        "slaty breasted rail",
        "estern water rail",
        "western water rail",
        "ruddy breasted crake",
        "brown crake",
        "black trailed crake",
        "spotted crake",
        "slatey legged crake",
        "white breasted waterhen",
        "watercock",
        "purple swamphen",
        "common moorhen",
        "cmmon coot",
        "baillon s crake"
    ],
    "Gruidae":[
        "sarus crane",
        "demoiselle crane",
        "common crane",
        "black necked crane"
    ],
    "Gaviidae":[
        "red throated loon"
    ],
    "Otididae":[
        "bengal florican",
        "lesser florican"
    ],
    "Ciconiidae":[
        "greater adjutant",
        "lesser adjutant",
        "painted stork",
        "asian openbill",
        "black strok",
        "asian woollyneck",
        "white stork",
        "black necked stork"
    ],
    "Threskiornithidae":[
        "eurasian spoonbill",
        "black headed ibis",
        "red naped ibis",
        "glossy ibis"
    ],
    "Ardeidae":[
        "eurasian bittern",
        "yellow bittern",
        "cinnamon bittern",
        "black bittern",
        "malay night heron",
        "black crowned night heron",
        "green backed herono",
        "indian pond heron",
        "cattle egret",
        "grey heron",
        "white bellied heron",
        "purple heron",
        "great white egret",
        "immediate egret",
        "little egret"
    ],
    "Pelecanidae":[
        "spot billed pelican",
        "great white pelican"
    ],
    "Phalacrocoracidae":[
        "little cormorant",
        "great cormorant",
        "indian cormorant"
    ],
    "Anhingidae":[
        "oriental darter"
    ],
    "Burhinidae":[
        "indian thick knee",
        "great thick knee"
    ],
    "Haematopodidae":[
        "eurasian oystercatcher"
    ],
    "Ibidorhynchidae":[
        "ibisbill"
    ],
    "Recurvirostridae":[
        "pied avocet",
        "black winged stilt"
    ],
    "Charadriidae":[
        "grey plover",
        "pacific golden plover",
        "long billed plover",
        "little ringed plover",
        "kentish plover",
        "lesser sandplover",
        "greater sandplover",
        "northern lapwing",
        "river lapwing",
        "yellow wattled lapwing",
        "grey headed lapwing",
        "red wattled lapwing",
        "white tailed lapwing"
    ],
    "Rostratulidae":[
        "greater painted snipe"
    ],
    "Jacanidae":[
        "pheasant tailed jacana",
        "bronze winged jacana"
    ],
    "Scolopacidae":[
        "red knot",
        "terek sandpiper",
        "red necked phalarope",
        "whimbrel",
        "eurasian curlew",
        "black tailed godwit",
        "ruddy turnstone",
        "ruff",
        "curlew sandpiper",
        "temminck s stint",
        "long toed stint",
        "sanderling",
        "dunlin",
        "little stint",
        "eurasian wookcock",
        "solitary snipe",
        "wood snipe",
        "pintail snipe",
        "common snipe",
        "jack snipe",
        "common greenshank",
        "common redshank",
        "wood sandpiper",
        "marsh sandpiper",
        "common sandpiper",
        "green sandpiper",
        "spotted redshank"
    ],
    "Turnicidae":[
        "common buttonquail",
        "yellow legged buttonquail",
        "barred buttonquail"
    ],
    "Glareolidae":[
        "indian courser",
        "orienteal pratincole",
        "little pratincole"
    ],
    "Laridae":[
        "indian skimmer",
        "broen headed gull",
        "black headed gull",
        "pallas s gull",
        "mew gull",
        "slender billed gull",
        "lesser black blacked gull",
        "little tern",
        "caspian tern",
        "whiskered tern",
        "white winged tern",
        "river tern",
        "common tern",
        "black bellied tern",
        "gul billed tern",
        "sooty tern"
    ],
    "Tytonidae":[
        "eastern grass owl",
        "common barn owl"
    ],
    "Strigidae":[
        "brown boobook",
        "collared owlet",
        "asian barred owlet",
        "jungle owlet",
        "spotted owlet",
        "little owlet",
        "collard scops owl",
        "indian scops owl",
        "mountain scops owl",
        "oriental scops owl",
        "short eared owl",
        "northern long eared owl",
        "brown wood owl",
        "himalayan owl",
        "mottled wood owl",
        "eurasian eagle owl",
        "rock eagle owl",
        "spot bellied eagle owl",
        "dusty eagle owl",
        "brown fish owl",
        "tawny fish owl"
    ],
    "Pandionidae":[
        "osprey"
    ],
    "Accipitridae":[
        "black winged kite",
        "oriental honey buzzard",
        "jerdon s baza",
        "black baza",
        "creasted serpent eagle",
        "short toed snake eagle",
        "bearded vulture",
        "red headed vulture",
        "himalayan griffon",
        "white rumped vulture",
        "slender billed vulture",
        "indian vulture",
        "griffon vulture",
        "cinereous vulture",
        "mountian hawk eagle",
        "changeable hawk eagle",
        "rufous bellied eagle",
        "black eagle",
        "indian spotted eagle",
        "greater spotted eagle",
        "tawny eagle",
        "steppe eagle",
        "eastern imperial eagle",
        "golden eagle",
        "bonelli s eagle",
        "booted eagle",
        "western marsh harrier",
        "easter marsh harrier",
        "hen harrier",
        "pallid harrier",
        "pied harrier",
        "montagu s harrier",
        "crested goshawk",
        "shikra",
        "besra",
        "eurasian sparrowhawk",
        "northern goshawk",
        "pallas s fish eagle",
        "white tailed sea eagle",
        "lesser fish eagle",
        "grey headed fish eagle",
        "brahminy kite",
        "black kite",
        "white eyed buzzard",
        "himalayan buzzard",
        "long legged buzzard",
        "upland buzzard",
        "egyptian vulture"
    ],
    "Trogonidae":[
        "red headed trogon"
    ],
    "Bucerotidae":[
        "great hornbill",
        "indian grey hornbill",
        "oriental pied hornbill",
        "rufous necked hornbill"
    ],
    "Upupidae":[
        "common hoopoe"
    ],
    "Meropidae":[
        "blue bearded bee eater",
        "asian green bee eater",
        "chestnut headed bee eater",
        "blue tailed bee eater"
    ],
    "Coraciidae":[
        "indian roller",
        "indochinese roller",
        "oriental dollarbird"
    ],
    "Alcedinidae":[
        "blue eared kingfisher",
        "common kingfisher",
        "crested kingfisher",
        "pied kingfisher",
        "stork billed kingfisher",
        "ruddy kingfisher",
        "white breasted kingfisher",
        "blyth s kingfisher",
        "black capped kingfisher"
    ],
    "Megalaimidae":[
        "coppersmith barbet",
        "blue eared barbet",
        "great barbet",
        "lineated barbet",
        "brown headed barbet",
        "golden throated barbet",
        "blue throated barbet"
    ],
    "Indicatoridae":[
        "yellow rumped honeyguide"
    ],
    "Picidae":[
        "eurasian wryneck",
        "white browned piculet",
        "speckled piculet",
        "bay woodpecker",
        "greater flameback",
        "white naped woodpecker",
        "himalayan flameback",
        "black rumped flameback",
        "pale headed woodpecker",
        "rufous woodpecker",
        "greater yellownape",
        "lesser yellownape",
        "streak throated woodpecker",
        "black naped woodpecker",
        "scaly bellied woodpecker",
        "great staty woodpecker",
        "grey cpped woodpecker",
        "indian pygmy woodpecker",
        "yellow crowned woodpecker",
        "brown fronted woodpecker",
        "scarlet breasted woodpecker",
        "rufous bellied woodpecker",
        "fulvous breasted woodpecker",
        "darjeeling woodpecker",
        "himalayan woodpecker"
    ],
    "Falconidae":[
        "collared falconet",
        "lesser kestrel",
        "common kestrel",
        "red headed falcon",
        "amur falcon",
        "merlin",
        "eurasian hobby",
        "oriental hobby",
        "lagger falcon",
        "saker falcon",
        "peregrine falcon"
    ],
    "Psittacidae":[
        "vernal hanging parrot",
        "slaty headed parakeet",
        "blosson headed parakeet",
        "plum headed parakeet",
        "red breated parakeet",
        "alexandrine parakeet",
        "rose ringed parakeet"
    ],
    "Pittidae":[
        "blue naped pitta",
        "indian pitta",
        "western hooded pitta"
    ],
    "Eurylaimidae":[
        "long tailed broadbill",
        "grey browed broadbill"
    ],
    "Oriolidae":[
        "maroon oriole",
        "black hooded oriole",
        "indian golden oriole",
        "slender billed oriole",
        "black naped oriole"
    ],
    "Vireonidae":[
        "black headed shrike babbler",
        "white browed shrike babbler",
        "green shrike babbler",
        "black eared shrike babbler",
        "white bellied erponis"
    ],
    "Campephagidae":[
        "small minivet",
        "grey chinned minivet",
        "short billed minivet",
        "long tailed minivet",
        "scarlet minivet",
        "rosy minivet",
        "ashy minivet",
        "swinhoe s minivet",
        "indian cuckooshrike",
        "black winged cuckooshrike",
        "black headed cuckooshrike"
    ],
    "Artamidae":[
        "ashy woodswallow"
    ],
    "Vangidae":[
        "bar winged flycatcher shrike",
        "large woodshrike",
        "common woodshrike"
    ],
    "Aegithinidae":[
        "common iora"
    ],
    "Rhipiduridae":[
        "white browed fantail",
        "white throated fantail"
    ],
    "Dicruridae":[
        "black drongo",
        "ashy drongo",
        "white bellied drongo",
        "crow billied drongo",
        "bronze drongo",
        "lesser racquet tailed drongo",
        "hair crested drongo",
        "greater racquet tailed drongo"
    ],
    "Monarchidae":[
        "black naped monarch",
        "indian paradise flycatcher"
    ],
    "Laniidae":[
        "brown shrike",
        "isabelline shrike",
        "bay backed shrike",
        "long tailed shrike",
        "grey backed shrike",
        "great grey shrike"
    ],
    "Corvidae":[
        "rufous treepie",
        "grey treepie",
        "red billed chough",
        "yellow billed chough",
        "yellow billed blue magpie",
        "red billed blue magpie",
        "common green magpie",
        "plain crowned jay",
        "black headed jay",
        "southern nutcraker",
        "common raven",
        "house crow",
        "large billed crow"
    ],
    "Stenostiridae":[
        "yellow bellied fairy fantail",
        "grey headed canary flycatcher"
    ],
    "Paridae":[
        "fire capped tit",
        "yellow browed tit",
        "sultan tit",
        "coal tit",
        "rufous naped tit",
        "rufous vented tit",
        "grey crested tit",
        "ground tit",
        "green backed tit",
        "great tit",
        "black lored tit",
        "yellow cheeked tit"
    ],
    "Alaudidae":[
        "rufous tailed lark",
        "ashy crowned sparrow lark",
        "horsfield s bushlark",
        "bengal bushlark",
        "sand lark",
        "hume s lark",
        "greater short toed lark",
        "horned lark",
        "oriental skylark",
        "crested lark",
        "tibetan lark",
        "eurasian skylark"
    ],
    "Cisticolidae":[
        "zitting cisticola",
        "golden headed cisticola",
        "striated prinia",
        "black throated prinia",
        "grey crowned prinia",
        "grey breasted prinia",
        "graceful prinia",
        "jungle prinia",
        "yellow bellied prinia",
        "ashy prinia",
        "plain prinia",
        "common tailorbird"
    ],
    "Acrocephalidae":[
        "thick billed warbler",
        "booted warbler",
        "black browed reed warbler",
        "blyth s reed warbler",
        "paddyfield warbler",
        "blunt winged warbler",
        "clamorous reed warbler",
        "moustached warbler",
        "oriental reed warbler"
    ],
    "Pnoepygidae":[
        "nepal cupwing",
        "pygmy cupwing",
        "scaly breasted cupwing"
    ],
    "Locustellidae":[
        "pallas s grasshopper warbler",
        "lanceolated warbler",
        "brown grasshopper warbler",
        "chinese grasshopper warbler",
        "spotted grasshopper warbler",
        "himalayan grasshopper warbler",
        "common grasshopper warbler",
        "baikal grasshopper warbler",
        "striated grassbird",
        "bristled grassbird"
    ],
    "Hirundinidae":[
        "asian house martin",
        "nepal house martin",
        "northern house martin",
        "streak throated swallow",
        "wire tailed swallow",
        "barn swallow",
        "red rumped swallow",
        "eurasian crag martin",
        "asian plain martin",
        "collared sand martin",
        "pale sand martin"
    ],
    "Pycnonotidae":[
        "white throated bulbul",
        "ashy bulbul",
        "mountain bulbul",
        "black bulbul",
        "striated bulbul",
        "black crested bulbul",
        "red whiskered bulbul",
        "himalayan bulbul",
        "red vented bulbul"
    ],
    "Scotocercidae":[
        "asian stubtail",
        "mountain tailorbird"
    ],
    "Phylloscopidae":[
        "yellow browed warbler",
        "hume s leaf warbler",
        "lemon rumped leaf warbler",
        "buff barred warbler",
        "ashy throated warbler",
        "dusky warbler",
        "smoky warbler",
        "siberian chiffchaff",
        "tytler s leaf warbler",
        "sulphur bellied warbler",
        "tickell s leaf warbler",
        "grey cheeked warbler",
        "green crowned warbler",
        "whistler s warbler",
        "chestnut crowned warbler",
        "greenish warbler",
        "large billed leaf warbler",
        "yellow vented warbler",
        "blyth s leaf warbler",
        "western crowned leaf warbler",
        "grey hooded warbler",
        "radde s warbler",
        "green warbler",
        "slaty bellied tesia",
        "grey bellied tesia",
        "chestnut headed tesia",
        "chestnut crowned bush warbler",
        "grey sided bush warbler",
        "pale footed bush warbler",
        "yellow bellied warbler",
        "rufous faced warbler",
        "black faced warbler",
        "broad billed warbler",
        "brownish flanked bush warbler",
        "hume s bush warbler",
        "aberrant bush warbler"
    ],
    "Aegithalidae":[
        "white browed tit warbler",
        "red headed tit",
        "white throated tit",
        "rufous fronted tit"
    ],
    "Sylviidae":[
        "lesser whitethroat",
        "eastern orphean warbler",
        "fire tailed myzornis",
        "golden breasted fulvetta",
        "yellow eyed babbler",
        "jerdon s babbler",
        "white browed fulvetta",
        "great parrotbill",
        "brown parrotbill",
        "fulvous parrotbill",
        "black throated parrotbill",
        "black breasted parrotbill"
    ],
    "Zosteropidae":[
        "black chinned yuhina",
        "stripe throated yuhina",
        "whiskered yuhina",
        "rufous vented yuhina",
        "white naped yuhina",
        "oriental white eye"
    ],
    "Timaliidae":[
        "rufous throated wren babbler",
        "blackish breasted babbler",
        "coral billed scimitar babbler",
        "slender billed scimitar babbler",
        "white browed scimitar babbler",
        "streak breasted scimitar babbler",
        "rusty cheeked scimitar babbler",
        "grey throated babbler",
        "tawny bellied babbler",
        "chestnut capped babbler",
        "pin striped tit babbler",
        "golden babbler",
        "black chinned babbler",
        "rufous capped babbler"
    ],
    "Pellorneidae":[
        "white hooded babbler",
        "rufous winged fulvetta",
        "swamp grass babbler",
        "puff throated babbler",
        "abbott s babbler",
        "long billed wren babbler",
        "indian grass bibbler"
    ],
    "Leiotrichidae":[
        "nepal fulvetta",
        "himalayan cutia",
        "striated babbler",
        "common babbler",
        "spiny babbler",
        "slender billed babbler",
        "jungle babbler",
        "large grey babbler",
        "striated laughingthrush",
        "lesser necklaced laughingthrush",
        "greater necklaced laughingthrush",
        "white crested laughingthrush",
        "spotted laughingthrush",
        "rufous chinned laughingthrush",
        "white throated laughingthrush",
        "grey sided laughingthrush",
        "rufous necked laughingthrush",
        "scaly laughingthrush",
        "blue winged laughingthrush",
        "streaked laughingthrush",
        "variegated laughingthrush",
        "black faced laughingthrush",
        "chestnut crowned laughingthrush",
        "long tailed sibia",
        "rufous sibia",
        "silver eared mesia",
        "red billed leiothrix",
        "rufous backed sibia",
        "red tailed minla",
        "red faced liocichla",
        "hoary throated barwing",
        "blue winged minla",
        "bar throated minla",
        "rusty fronted barwing"
    ],
    "Certhiidae":[
        "rusty flanked treecreeper",
        "sikkim treecreeper",
        "bar tailed treecreper",
        "hodgso s treecreeper"
    ],
    "Sittidae":[
        "kashmir nuthatch",
        "indian nuthatch",
        "chestnut bellied nuthatch",
        "white tailed nuthatch",
        "white cheeked nuthatch",
        "velvet fronted nuthatch",
        "wallcreeper"
    ],
    "Troglodytidae":[
        "northern wren"
    ],
    "Cinclidae":[
        "white throated dipper",
        "brown dipper"
    ],
    "Sturnidae":[
        "common starling",
        "rosy starling",
        "asian pied starling",
        "brahminy starling",
        "chestnut tailed starling",
        "white shouldered starling",
        "common myna",
        "bank myna",
        "jungle myna",
        "great myna",
        "spot winged starling",
        "common hill myna",
        "purple backed starling",
        "asian glossy starling"
    ],
    "Turdidae":[
        "grandala",
        "long tailed thrush",
        "alpine thrush",
        "dark sided thrush",
        "long billed thrush",
        "scaly thrush",
        "purple cochoa",
        "green cochoa",
        "pied thrush",
        "orange headed thrush",
        "mistle thrush",
        "grey winged blackbird",
        "tickell s thrush",
        "tibetan blackbird",
        "white collared blackbird",
        "chestnut thrush",
        "dusky thrush",
        "black throated thrush",
        "rufous throated thrush",
        "eyebrowed thrush",
        "white backed thrush",
        "grey sided thrush"
    ],
    "Muscicapidae":[
        "oriental magpie robin",
        "indian robin",
        "white rumped shama",
        "dark sided flycatcher",
        "asian brown flycatcher",
        "brown breasted flycatcher",
        "ferruginous flycatcher",
        "rufous belied niltava",
        "small niltava",
        "large niltava",
        "verditer flycatcher",
        "white gorgeted flycatcher",
        "pale blue flycatcher",
        "pale chinned flycatcher",
        "tickell s blue flycatcher",
        "blue throated blue flycatcher",
        "gould s shortwing",
        "lesser shortwing",
        "himalayan shortwing",
        "indian blue robin",
        "siberian blue robin",
        "white bellied redstart",
        "bluethroat",
        "siberian rubythroat",
        "himalayan rubythroat",
        "chinese rubythroat",
        "white tailed blue robin",
        "rufous breasted bush robin",
        "himalayan bush robin",
        "white browed bush robin",
        "golden bush robin",
        "little forktail",
        "slaty backed forktail",
        "black backed forktail",
        "spotted forktail",
        "blue whistling thrush",
        "slaty backed flycatcher",
        "slaty blue flycatcher",
        "snowy browed flycatcher",
        "pygmy blue flycatcher",
        "rufous gorgeted flycatcher",
        "sapphire flycatcher",
        "ultramarine flycatcher",
        "little pied flycatcher",
        "rusty tailed flycatcher",
        "red throated flycatcher",
        "red breasted flycatcher",
        "kashmir flycatcher",
        "eversmann s redstart",
        "blue fronted redstart",
        "blue capped redstart",
        "white throated redstart",
        "white capped water redstart",
        "plumbeous water redstart",
        "black redstart",
        "white winged redstart",
        "hodgson s redstart",
        "daurian redstart",
        "blue capped rock thrush",
        "chestnu bellied rock thrush",
        "blue rock thrush",
        "rufous tailed rock thrush",
        "jerdon s bushchat",
        "grey bushchat",
        "white throated bushchat",
        "pied bushchat",
        "white tailed stonechat",
        "common stonechat",
        "northern wheatear",
        "isabelline wheatear",
        "pied wheatear",
        "variable wheatear",
        "red tailed wheatear",
        "desert wheatear",
        "brown rockchat"
    ],
    "Regulidae":[
        "goldrest"
    ],
    "Bombycillidae":[
        "bohemian waxwing"
    ],
    "Elachuridae":[
        "spotted elachura"
    ],
    "Irenidae":[
        "asian fairy bluebird"
    ],
    "Chloropseidae":[
        "golden fronted leafbird",
        "orange bellied leafbird"
    ],
    "Dicaeidae":[
        "yellow bellied flowerpecker",
        "yellow vented flowerpecker",
        "thick billed flowerpecker",
        "pale billed flowerpecker",
        "plain flowerpecker",
        "scarlet backed flowerpecker",
        "fire breasted flowerpecker"
    ],
    "Nectariniidae":[
        "little spiderhunter",
        "streaked spiderhunter",
        "ruby cheeked sunbird",
        "purple sunbird",
        "fire tailed sunbird",
        "black throated sunbird",
        "green tailed sunbird",
        "gould s sunbird",
        "crimson sunbird"
    ],
    "Prunellidae":[
        "altai acentor",
        "alpine acentor",
        "maroon backed accentor",
        "robin accentor",
        "rufous breasted accentor",
        "brown accentor",
        "black throated accentor"
    ],
    "Ploceidae":[
        "black breasted weaver",
        "streaked weaver",
        "baya weaver",
        "finn s weaver"
    ],
    "Estrildidae":[
        "red avadavat",
        "indian silverbill",
        "white rumped munia",
        "scaly breasted munia",
        "chestnut munia",
        "tricolored munia"
    ],
    "Passeridae":[
        "house sparrow",
        "russet sparrow",
        "eurasian tree sparrow",
        "chestnut shouldered bush sparrow",
        "spanish sparrow",
        "black winged snowfinch",
        "white rumped snowfinch",
        "plain backed snowfinch",
        "rufous necked snowfinch"
    ],
    "Motacillidae":[
        "tree pipit",
        "olive backed pipit",
        "red throated pipit",
        "rosy pipit",
        "water pipit",
        "upland pipit",
        "richard s pipit",
        "paddyfield pipit",
        "blyth s pipit",
        "long billed pipit",
        "tawny pipit",
        "buff bellied pipit",
        "western yellow wagtail",
        "grey wagtail",
        "citrine wagtail",
        "white browed wagtail",
        "white wagtail",
        "forest wagtail"
    ],
    "Fringillidae":[
        "common chaffinch",
        "brambling",
        "black and yellow grosbeak",
        "collared groasbeak",
        "spot winged grosbeak",
        "white winged grosbeak",
        "common rosefinch",
        "scarlet finch",
        "beautiful rosefinch",
        "dark rumped rosefinch",
        "pink browed rosefinch",
        "vinaceous rosefinch",
        "streaked rosefinch",
        "great rosefinch",
        "red fronted rosefinch",
        "crimson browed finch",
        "himalayan white browed rosefinch",
        "brown bullfinch",
        "red headed bullfinch",
        "grey headed bullfinch",
        "blanford s rosefinch",
        "spactacled finch",
        "gold naped finch",
        "dark breasted rosefinch",
        "plain mountain finch",
        "brandt s mountain finch",
        "yellow breasted greenfinch",
        "twite",
        "red crossbill",
        "eastern goldfinch",
        "red fronted serin",
        "tibetan siskin",
        "common linnet",
        "eurasian siskin",
        "mongolian finch",
        "spot winged rosefinch"
    ],
    "Emberizidae":[
        "crested bunting",
        "black headed bunting",
        "red headed bunting",
        "chestnut eared bunting",
        "rock bunting",
        "pine bunting",
        "yellow breasted bunting",
        "little bunting",
        "black faced bunting",
        "chestnut bunting",
        "yellowhammer",
        "grey necked bunting",
        "white capped bunting",
        "rustic bunting",
        "reed bunting"
    ]
} 
